<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2239b4d0-02fd-45c9-ae85-38e6503ab4fa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.21" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.2.13" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="NCrontab" Version="3.4.0" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="Resend" Version="0.2.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
  </ItemGroup>

</Project>
